project:
  type: website
  output-dir: "docs/"
  render:
  - "*.qmd"
  - "!resources/"
  - "!common/"
  - "!slides/"
  - "!assignments/"
  pre-render:
    - "touch schedule.qmd"
    - build_pdf_slides.R
    - build_posts.R
  post-render:
    - "cp -rf resources/ docs/resources/"
    - "cp -rf assignments/ docs/assignments/"
    - "cp -rf slides/ docs/slides/"

website:
  announcement:
    content: "Our first meetup will be Monday, August 31st at 7:00pm. [Click here to join.](https://us02web.zoom.us/j/84988569164?pwd=FWEeLQ4WRFU3uyJ6pNNh7dCyrlTFsZ.1)"
  #   content: "[Click here]() to the join the Slack channel."
  #   # position: below-navbar # above-navbar or below-navbar
  #   icon: slack #info-circle # https://icons.getbootstrap.com
  #   dismissable: false
  #   type: primary # primary, secondary, success, danger, warning, info, light, dark

  page-navigation: true
  title: "IS382 Predictive Modeling"
  description: "CUNY School of Professional Studies"
  # TODO: Update for each semester
  site-url: "https://fall2026.is382.net"

# TODO: Update for each semester
  repo-url: https://jbryer.github.io/IS382-2026-Fall/
  repo-subdir: website
  repo-branch: master
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    # right: ""
    # left: ""
    background: "#325A89"

  sidebar:
    background: "#eeeeee"
    logo: "course_logo.png" # TODO: Replace with course logo
    pinned: true
    align: center
    # List of available icons: https://icons.getbootstrap.com
    tools:
      - icon: calendar-check
        href: schedule.qmd
        text: "Schedule"
      - icon: book
        href: textbooks.qmd
        text: "Textbooks"
# TODO: Update for each semester
      - icon: github
        href: https://github.com/jbryer/IS382-2026-Fall
        text: "Github"
        target: _blank
# TODO: Update for each semester
        # - icon: slack
      - icon: link-45deg
        text: "CUNY"
        menu:
          - text: Brightspace LMS
            url: https://brightspace.cuny.edu
            target: _blank
          - text: MSDS Program Page
            url: https://sps.cuny.edu/academics/graduate/master-science-data-science-ms
            target: _blank
          - text: CUNYfirst
            url: https://cunyfirst.cuny.edu
            target: _blank
# TODO: Update for new instructor
      - icon: envelope
        text: "Email"
        url: mailto:jason.bryer@cuny.edu?subject=IS382

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: "Announcements"
      - href: schedule.qmd
        text: "Schedule"
      - section: "Course information"
        contents:
          - href: syllabus.qmd
            text: "Syllabus"
          - href: instructor.qmd
            text: "Instructor"
          - href: project.qmd
            text: "Data Project"
          - href: software.qmd
            text: "Software"
          - href: textbooks.qmd
            text: "Textbooks"
      - section: "Topics"
        contents:
          - href: modules/00-Intro_to_Course.qmd
            text: "Introduction to the course"
          - href: modules/01-Intro_to_Modeling.qmd
            text: "1 - Introduction to Modeling"
          - href: modules/02-Linear_Regression.qmd
            text: "2 - Linear regression"
          - href: modules/03-Multiple_Regression.qmd
            text: "3 - Multiple regression"
          - href: modules/04-Logistic_Regression.qmd
            text: "4 - Logistic Regression"
          - href: modules/05-Generative_Models.qmd
            text: "5 - Generative Models for Classification"
          - href: modules/06-Resampling_Methods.qmd
            text: "6 - Resampling Methods"
          - href: modules/07-Tree_Models.qmd
            text: "7 - Tree Based Methods"
          - href: modules/08-Bagging_and_Random_Forests.qmd
            text: "8 - Bagging and Random Forests"
          - href: modules/09-Support_Vector_Machines.qmd
            text: "9 - Support Vector Machines"
          - href: modules/10-Principal_Component_Analysis.qmd
            text: "10 - Principal Component Analysis"
          - href: modules/11-Cluster_Methods.qmd
            text: "11 - Clustering Methods"
          - href: modules/12-Missing_Data.qmd
            text: "12 - Missing data"
          - href: modules/13-Bayesian_Analysis.qmd
            text: "13 - Bayesian Analysis"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: false
    # include-in-header:
    #   text: |
    #     <link href="/fullcalendar-lib/main.css" rel="stylesheet" />
    #     <script type="text/javascript" src="/fullcalendar-lib/main.js"></script>

freeze: auto

editor: source
